/** Quiet Ledger PDF service: real browser-side page operations use pdf-lib; text inspection uses pdf.js lazily and can later be replaced by a server conversion adapter. */
import { PDFDocument, degrees, rgb, StandardFonts } from "pdf-lib";
import type { PdfAnnotation, PdfProject } from "./pdfModels";

const bytesToBlob = (bytes: Uint8Array) => new Blob([bytes.buffer], { type: "application/pdf" });
export const downloadBlob = (blob: Blob, filename: string) => { const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click(); window.setTimeout(() => URL.revokeObjectURL(url), 1000); };
export async function createBlankPdf() { const pdf = await PDFDocument.create(); pdf.addPage([612, 792]); return bytesToBlob(await pdf.save()); }
async function mutatePdf(blob: Blob, mutate: (pdf: PDFDocument) => Promise<void> | void) { const pdf = await PDFDocument.load(await blob.arrayBuffer()); await mutate(pdf); return bytesToBlob(await pdf.save()); }
export const pdfOperations = {
  addPage: (blob: Blob) => mutatePdf(blob, pdf => { pdf.addPage([612, 792]); }),
  deletePage: (blob: Blob, index: number) => mutatePdf(blob, pdf => { if (pdf.getPageCount() <= 1) throw new Error("A PDF needs at least one page."); pdf.removePage(index); }),
  duplicatePage: async (blob: Blob, index: number) => { const source = await PDFDocument.load(await blob.arrayBuffer()); const target = await PDFDocument.create(); const copied = await target.copyPages(source, Array.from({ length: source.getPageCount() }, (_, page) => page)); copied.forEach((page, position) => { target.addPage(page); if (position === index) target.addPage(page); }); return bytesToBlob(await target.save()); },
  reorder: async (blob: Blob, order: number[]) => { const source = await PDFDocument.load(await blob.arrayBuffer()); const target = await PDFDocument.create(); const pages = await target.copyPages(source, order); pages.forEach(page => target.addPage(page)); return bytesToBlob(await target.save()); },
  rotate: (blob: Blob, index: number, amount = 90) => mutatePdf(blob, pdf => { const page = pdf.getPage(index); page.setRotation(degrees((page.getRotation().angle + amount) % 360)); }),
  extract: async (blob: Blob, indexes: number[]) => { const source = await PDFDocument.load(await blob.arrayBuffer()); const target = await PDFDocument.create(); const pages = await target.copyPages(source, indexes); pages.forEach(page => target.addPage(page)); return bytesToBlob(await target.save()); },
  merge: async (blobs: Blob[]) => { const target = await PDFDocument.create(); for (const blob of blobs) { const source = await PDFDocument.load(await blob.arrayBuffer()); const pages = await target.copyPages(source, Array.from({ length: source.getPageCount() }, (_, page) => page)); pages.forEach(page => target.addPage(page)); } return bytesToBlob(await target.save()); },
};
export async function applyAnnotations(blob: Blob, annotations: PdfAnnotation[]) { return mutatePdf(blob, async pdf => { const font = await pdf.embedFont(StandardFonts.Helvetica); annotations.forEach(annotation => { const page = pdf.getPages()[annotation.page]; if (!page) return; const { height } = page.getSize(); const x = annotation.x; const y = height - annotation.y - annotation.height; const color = annotation.color === "#3158c9" ? rgb(.19, .35, .79) : annotation.color === "#e4b83f" ? rgb(.89, .72, .25) : rgb(.72, .23, .26); if (annotation.kind === "text") page.drawText(annotation.text || "Note", { x, y: height - annotation.y, size: 12, color, font }); else if (annotation.kind === "underline") page.drawLine({ start: { x, y: height - annotation.y }, end: { x: x + annotation.width, y: height - annotation.y }, thickness: 2, color }); else if (annotation.kind === "arrow" || annotation.kind === "draw") page.drawLine({ start: { x, y: height - annotation.y }, end: { x: x + annotation.width, y }, thickness: 2, color }); else if (annotation.kind === "circle") page.drawEllipse({ x: x + annotation.width / 2, y: y + annotation.height / 2, xScale: annotation.width / 2, yScale: annotation.height / 2, borderColor: color, borderWidth: 2 }); else page.drawRectangle({ x, y, width: annotation.width, height: annotation.height, borderColor: color, borderWidth: annotation.kind === "highlight" ? 0 : 2, color: annotation.kind === "highlight" ? color : undefined, opacity: annotation.kind === "highlight" ? .22 : undefined }); }); }); }
export async function inspectPdf(blob: Blob) { const pdfjs = await import("pdfjs-dist/legacy/build/pdf.mjs"); const task = pdfjs.getDocument({ data: await blob.arrayBuffer() }); const document = await task.promise; const textByPage: string[] = []; for (let index = 1; index <= document.numPages; index += 1) { const page = await document.getPage(index); const content = await page.getTextContent(); textByPage.push(content.items.map(item => "str" in item ? item.str : "").join(" ")); } return { pageCount: textByPage.length, textByPage }; }
export const exportService = { status: "local" as const, downloadPdf: (blob: Blob, name: string) => downloadBlob(blob, name.endsWith(".pdf") ? name : `${name}.pdf`), unavailable: (format: string) => ({ status: "unavailable" as const, message: `${format} export requires the conversion service to be configured.` }) };
