/** Quiet Ledger public page: editorial positioning makes OfficeFlow feel like a composed system, not a generic SaaS pitch. */
import { ArrowRight, Check, File, FileSpreadsheet, FileText, LayoutTemplate, Presentation, Sparkles, WandSparkles } from "lucide-react";
import { Link } from "wouter";
import { FileVisual } from "@/components/officeflow/FileVisual";
import { PublicMark } from "@/components/officeflow/WorkspaceLayout";

const workTypes = [{ type: "document" as const, name: "Documents", detail: "Write with focus" }, { type: "spreadsheet" as const, name: "Spreadsheets", detail: "Make sense of numbers" }, { type: "presentation" as const, name: "Presentations", detail: "Tell a clear story" }, { type: "pdf" as const, name: "PDFs", detail: "Keep every format close" }];
const features = ["Powerful editors", "AI assistance", "Cloud workspace", "Templates", "File organization", "Collaboration"];
export default function LandingPage() { return <div className="of-landing"><header className="of-public-nav"><Link href="/"><PublicMark /></Link><nav><a href="#workspace">Workspace</a><a href="#intelligence">AI</a><a href="#templates">Templates</a></nav><div><Link href="/login" className="of-public-login">Sign in</Link><Link href="/signup" className="of-public-cta">Create for free <ArrowRight size={15} /></Link></div></header><main><section className="of-hero"><div className="of-hero-copy"><p className="of-kicker"><span /> ONE INTELLIGENT WORKSPACE</p><h1>Everything you create.<br /><em>One intelligent workspace.</em></h1><p>Create documents, spreadsheets, presentations and PDFs in one beautifully connected workspace — with AI built in.</p><div className="of-hero-actions"><Link href="/signup" className="of-action-primary">Create for free <ArrowRight size={17} /></Link><Link href="/dashboard" className="of-action-secondary">Explore workspace</Link></div><div className="of-hero-note"><span><Check size={14} /></span> No credit card. A browser workspace is ready to explore.</div></div><div className="of-hero-visual" aria-label="OfficeFlow dashboard preview"><div className="of-visual-top"><div className="of-visual-brand"><i /><b>Office<span>Flow</span></b></div><span>Good morning</span><span className="of-visual-avatar">OF</span></div><div className="of-visual-body"><aside><span className="is-on">Home</span><span>My files</span><span>Recent</span><span>Starred</span><button>+ New</button></aside><section><p className="of-visual-index">START A NEW FILE</p><div className="of-visual-create">{workTypes.map(item => <div key={item.type}><FileVisual type={item.type} size="sm" /><span>{item.name}</span></div>)}</div><div className="of-visual-recent"><header><b>Recent work</b><span>View all</span></header>{["Q3 planning brief", "Operating budget", "Product narrative"].map((name, index) => <div key={name}><FileVisual type={workTypes[index].type} size="sm" /><b>{name}</b><small>{index + 1} day{index ? "s" : ""} ago</small></div>)}</div></section></div></div></section>
  <section id="workspace" className="of-worktypes"><div className="of-worktypes-copy"><p className="of-kicker"><span /> ONE SYSTEM, MANY WAYS TO THINK</p><h2>All your work.<br /><em>One place.</em></h2><p>Switch from the first thought to the final file without breaking your flow. Every format has a home, an identity, and room to grow.</p></div><div className="of-worktypes-list">{workTypes.map((item, index) => <article key={item.type}><span className="of-worktype-num">0{index + 1}</span><FileVisual type={item.type} size="lg" /><div><h3>{item.name}</h3><p>{item.detail}</p></div><ArrowRight size={19} /></article>)}</div></section>
  <section className="of-feature-band"><div className="of-feature-lead"><p className="of-kicker"><span /> BUILT FOR GETTING THINGS DONE</p><h2>Give every good<br />idea a better way<br />forward.</h2></div><div className="of-feature-list">{features.map((feature, index) => <div key={feature}><span>0{index + 1}</span><strong>{feature}</strong><i /></div>)}</div></section>
  <section id="intelligence" className="of-ai-feature"><div className="of-ai-orbit"><div className="of-orbit-ring one" /><div className="of-orbit-ring two" /><div className="of-ai-symbol"><Sparkles size={38} /></div><span className="of-ai-bubble bubble-a">Summarize this document.</span><span className="of-ai-bubble bubble-b">Analyze this spreadsheet.</span><span className="of-ai-bubble bubble-c">Turn this report into a presentation.</span></div><div><p className="of-kicker"><span /> INTELLIGENCE, WHERE IT HELPS</p><h2>AI that works<br /><em>with your files.</em></h2><p>Start with an intention, a question, or a source file. OfficeFlow is architected to connect an AI provider directly to the work already in front of you.</p><Link href="/dashboard" className="of-text-link">Explore the workspace <ArrowRight size={16} /></Link></div></section>
  <section id="templates" className="of-final-cta"><div><p className="of-kicker"><span /> A CLEARER WAY TO BEGIN</p><h2>Your workspace<br />is ready.</h2><p>Open the quiet, capable place for every file you are ready to make.</p><Link href="/signup" className="of-action-primary">Get started <ArrowRight size={17} /></Link></div><div className="of-cta-stack"><article><FileText size={25} /><span>Write</span></article><article><FileSpreadsheet size={25} /><span>Calculate</span></article><article><Presentation size={25} /><span>Present</span></article><article><File size={25} /><span>Organize</span></article></div></section></main><footer className="of-public-footer"><PublicMark /><span>Everything you create. One intelligent workspace.</span><div><Link href="/login">Sign in</Link><Link href="/dashboard">Workspace</Link></div></footer></div>; }
