/** Quiet Ledger Copilot panel: a shared conversation surface that exposes provider readiness honestly instead of generating fabricated responses. */
import { useEffect, useRef, useState } from "react";
import { ArrowUp, Copy, Paperclip, RotateCcw, Sparkles, Square, Trash2, X } from "lucide-react";
import { toast } from "sonner";
import { aiProvider, aiSuggestions, type AIContext, type AIMessage } from "@/lib/aiProvider";

export function AICommandPanel({ open, onClose, context }: { open: boolean; onClose: () => void; context?: AIContext }) {
  const [prompt, setPrompt] = useState(""); const [messages, setMessages] = useState<AIMessage[]>([]); const [loading, setLoading] = useState(false); const controller = useRef<AbortController | null>(null); const input = useRef<HTMLTextAreaElement>(null); const provider = aiProvider.status();
  useEffect(() => { if (open) requestAnimationFrame(() => input.current?.focus()); }, [open]);
  const ask = async () => { if (!prompt.trim() || loading) return; const message: AIMessage = { id: crypto.randomUUID(), role: "user", content: prompt.trim(), createdAt: new Date().toISOString() }; setMessages(current => [...current, message]); setPrompt(""); controller.current = new AbortController(); setLoading(true); try { const reply = await aiProvider.generateText(message.content, context, controller.current.signal); setMessages(current => [...current, { id: crypto.randomUUID(), role: "assistant", content: reply, createdAt: new Date().toISOString() }]); } catch (error) { const content = error instanceof Error ? error.message : "Something went wrong. Try again."; setMessages(current => [...current, { id: crypto.randomUUID(), role: "system", content, createdAt: new Date().toISOString() }]); } finally { setLoading(false); controller.current = null; } };
  const copyMessage = async (message: AIMessage) => { try { await navigator.clipboard.writeText(message.content); toast.success("Copied to clipboard"); } catch { toast.error("Unable to copy this message."); } };
  if (!open) return null;
  return <div className="of-overlay" role="presentation" onMouseDown={onClose}><section className="of-ai-panel of-copilot" role="dialog" aria-modal="true" aria-label="Ask OfficeFlow AI" onMouseDown={event => event.stopPropagation()}><header><div className="of-ai-title"><span><Sparkles size={17} /></span><div><p className="of-index">OFFICEFLOW AI</p><h2>Copilot</h2></div></div><button className="of-close" onClick={onClose} aria-label="Close AI panel"><X size={18} /></button></header><div className={provider.configured ? "of-ai-provider is-ready" : "of-ai-provider"}><b>{provider.configured ? "Provider connected" : "AI provider not configured"}</b><p>{provider.message}</p></div>{context?.fileName && <div className="of-ai-context"><Paperclip size={14} /><span>Using context: <b>{context.fileName}</b></span></div>}<div className="of-ai-history">{messages.length ? messages.map(message => <article key={message.id} className={`is-${message.role}`}><span>{message.role === "user" ? "You" : message.role === "assistant" ? "OfficeFlow AI" : "System"}</span><p>{message.content}</p>{message.role !== "user" && <button onClick={() => copyMessage(message)} title="Copy message"><Copy size={13} /></button>}</article>) : <div className="of-ai-empty"><Sparkles size={22} /><b>Bring an intent, not a blank page.</b><p>OfficeFlow AI is ready to use the current file context once a secure provider is connected.</p></div>}{loading && <article className="is-system"><span>OfficeFlow AI</span><p>OfficeFlow AI is thinking…</p></article>}</div><div className="of-ai-starters">{aiSuggestions.map(starter => <button key={starter} onClick={() => { setPrompt(starter); input.current?.focus(); }}>{starter}</button>)}</div><div className="of-ai-composer"><textarea ref={input} value={prompt} onChange={event => setPrompt(event.target.value)} placeholder="Ask OfficeFlow AI…" rows={3} onKeyDown={event => { if ((event.metaKey || event.ctrlKey) && event.key === "Enter") ask(); }} /><button disabled={!prompt.trim() || loading} onClick={ask} aria-label="Submit AI request"><ArrowUp size={18} /></button></div><footer><button onClick={() => { if (loading) controller.current?.abort(); }} disabled={!loading}><Square size={12} /> Stop</button><button onClick={() => { const last = messages.filter(message => message.role === "user").at(-1); if (last) { setPrompt(last.content); input.current?.focus(); } }} disabled={!messages.some(message => message.role === "user")}><RotateCcw size={12} /> Regenerate</button><button onClick={() => setMessages([])} disabled={!messages.length}><Trash2 size={12} /> Clear</button><span><kbd>⌘</kbd><kbd>↵</kbd> send · <kbd>⌘</kbd><kbd>J</kbd> open</span></footer></section></div>;
}
