/** Quiet Ledger file browser: local data actions are usable now and carefully distinguish browser storage from cloud operations. */
import { useMemo, useState } from "react";
import { Check, ChevronDown, Folder, FolderOpen, Grid2X2, List, MoreHorizontal, MoveRight, Search, Share2, Star, Trash2, Download, RotateCcw, Pencil, X, FilePlus2 } from "lucide-react";
import { useLocation } from "wouter";
import { toast } from "sonner";
import { useWorkspace } from "@/contexts/WorkspaceContext";
import { fileTypeLabel, formatSize, relativeDate, type OfficeFile } from "@/lib/officeflow";
import { FileVisual } from "./FileVisual";
import { loadBinary } from "@/lib/binaryStorage";
import { downloadBlob } from "@/lib/pdfService";

export type FileScope = "all" | "recent" | "starred" | "shared" | "trash";
export function FileBrowser({ scope = "all", heading = "My files", description = "Keep your working files close and your next action clear." }: { scope?: FileScope; heading?: string; description?: string }) {
  const { files, folders, viewMode, setViewMode, selectedIds, setSelectedIds, updateFile, deleteFiles, restoreFiles, moveFiles, renameFolder, deleteFolder } = useWorkspace(); const [, setLocation] = useLocation();
  const [search, setSearch] = useState(""); const [activeFolder, setActiveFolder] = useState<string | null>(null); const [menu, setMenu] = useState<string | null>(null);
  const visibleFiles = useMemo(() => files.filter(file => { const textMatch = file.name.toLowerCase().includes(search.toLowerCase()); if (!textMatch) return false; if (scope === "trash") return file.trashed; if (file.trashed) return false; if (scope === "starred") return file.starred; if (scope === "shared") return file.shared; if (scope === "recent") return true; return activeFolder ? file.parentFolderId === activeFolder : true; }).sort((a, b) => new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime()), [files, search, scope, activeFolder]);
  const visibleFolders = folders.filter(folder => scope === "all" && !search && folder.parentFolderId === activeFolder);
  const toggle = (id: string) => setSelectedIds(selectedIds.includes(id) ? selectedIds.filter(item => item !== id) : [...selectedIds, id]);
  const selectAll = () => setSelectedIds(selectedIds.length === visibleFiles.length ? [] : visibleFiles.map(file => file.id));
  const open = (file: OfficeFile) => setLocation(`/${file.type === "image" || file.type === "other" ? "document" : file.type}/new?file=${file.id}`);
  const rename = (file: OfficeFile) => { const next = window.prompt("Rename file", file.name); if (next?.trim()) { updateFile(file.id, { name: next.trim() }); toast.success("File renamed"); } };
  const move = (ids: string[]) => { const destinations = ["Root folder", ...folders.map(folder => folder.name)]; const response = window.prompt(`Move to:\n${destinations.map((name, i) => `${i + 1}. ${name}`).join("\n")}`, "1"); const choice = Number(response) - 1; if (!Number.isFinite(choice) || choice < 0 || choice >= destinations.length) return; moveFiles(ids, choice === 0 ? null : folders[choice - 1].id); toast.success("Moved in this browser workspace"); };
  const remove = (ids: string[]) => { const permanent = scope === "trash"; if (!window.confirm(permanent ? "Permanently remove these files from this browser workspace?" : "Move these files to trash?")) return; deleteFiles(ids, permanent); toast.success(permanent ? "Files permanently removed" : "Moved to trash"); };
  const download = async (file?: OfficeFile) => { if (!file) return toast.info("Choose one file to download."); const binary = await loadBinary(file.id); if (binary) { downloadBlob(binary, file.name); toast.success("Preparing your file for download"); return; } toast.info("Open this OfficeFlow file to export its current content from the editor."); };
  return <div className="of-page"><div className="of-page-head"><div><p className="of-index">FILE SYSTEM</p><h1>{heading}</h1><p>{activeFolder ? `Inside ${folders.find(folder => folder.id === activeFolder)?.name || "folder"}` : description}</p></div><div className="of-view-actions"><label className="of-inline-search"><Search size={16} /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Find a file" aria-label="Search files" /></label><div className="of-view-toggle" aria-label="File view"><button className={viewMode === "grid" ? "is-active" : ""} onClick={() => setViewMode("grid")} aria-label="Grid view"><Grid2X2 size={17} /></button><button className={viewMode === "list" ? "is-active" : ""} onClick={() => setViewMode("list")} aria-label="List view"><List size={18} /></button></div></div></div>
    {selectedIds.length > 0 && <div className="of-context-bar"><span><b>{selectedIds.length}</b> selected</span><div><button onClick={() => toast.info("Sharing requires a connected collaboration provider. The permission interface is available from file actions.")}><Share2 size={16} /> Share</button><button onClick={() => move(selectedIds)}><MoveRight size={16} /> Move</button><button onClick={() => download(visibleFiles.find(file => file.id === selectedIds[0]))}><Download size={16} /> Download</button><button className="is-danger" onClick={() => remove(selectedIds)}><Trash2 size={16} /> Delete</button><button aria-label="Clear selection" onClick={() => setSelectedIds([])}><X size={16} /></button></div></div>}
    {activeFolder && <button className="of-back-folder" onClick={() => setActiveFolder(null)}>← All files</button>}
    {visibleFolders.length > 0 && <section className="of-folder-area"><p className="of-section-label">FOLDERS</p><div className="of-folders">{visibleFolders.map(folder => <article key={folder.id} className="of-folder-card"><button className="of-folder-open" onClick={() => setActiveFolder(folder.id)}><Folder size={23} /><span><strong>{folder.name}</strong><small>{files.filter(file => file.parentFolderId === folder.id && !file.trashed).length} files</small></span></button><div className="of-row-menu"><button onClick={() => setMenu(menu === folder.id ? null : folder.id)} aria-label={`Actions for ${folder.name}`}><MoreHorizontal size={18} /></button>{menu === folder.id && <div className="of-mini-menu"><button onClick={() => { const name = window.prompt("Rename folder", folder.name); if (name?.trim()) renameFolder(folder.id, name.trim()); setMenu(null); }}>Rename</button><button className="is-danger" onClick={() => { if (window.confirm("Delete this folder? Files will return to root.")) deleteFolder(folder.id); setMenu(null); }}>Delete folder</button></div>}</div></article>)}</div></section>}
    {visibleFiles.length === 0 ? <div className="of-empty"><span><FolderOpen size={26} /></span><h2>{search ? "Nothing found" : scope === "trash" ? "Trash is empty" : "Your workspace is empty"}</h2><p>{search ? "Try a different name or clear the search." : "Create your first document and start building."}</p>{scope !== "trash" && <button onClick={() => setLocation("/document/new")}><FilePlus2 size={17} /> Create document</button>}</div> : viewMode === "grid" ? <div className="of-file-grid">{visibleFiles.map(file => <FileCard key={file.id} file={file} selected={selectedIds.includes(file.id)} onToggle={() => toggle(file.id)} onOpen={() => open(file)} onMenu={() => setMenu(menu === file.id ? null : file.id)} menuOpen={menu === file.id} onCloseMenu={() => setMenu(null)} onRename={() => rename(file)} onMove={() => move([file.id])} onDownload={() => download(file)} onDelete={() => remove([file.id])} onRestore={() => { restoreFiles([file.id]); toast.success("File restored"); }} onStar={() => updateFile(file.id, { starred: !file.starred })} />)}</div> : <div className="of-file-table"><div className="of-file-table-head"><label><input type="checkbox" checked={visibleFiles.length > 0 && selectedIds.length === visibleFiles.length} onChange={selectAll} aria-label="Select all files" /></label><span>Name</span><span>Owner</span><span>Modified</span><span>Location</span><span /></div>{visibleFiles.map(file => <FileRow key={file.id} file={file} selected={selectedIds.includes(file.id)} onToggle={() => toggle(file.id)} onOpen={() => open(file)} onMenu={() => setMenu(menu === file.id ? null : file.id)} menuOpen={menu === file.id} onCloseMenu={() => setMenu(null)} onRename={() => rename(file)} onMove={() => move([file.id])} onDownload={() => download(file)} onDelete={() => remove([file.id])} onRestore={() => { restoreFiles([file.id]); toast.success("File restored"); }} onStar={() => updateFile(file.id, { starred: !file.starred })} folders={folders} />)}</div>}</div>;
}

type CardProps = { file: OfficeFile; selected: boolean; onToggle: () => void; onOpen: () => void; onMenu: () => void; menuOpen: boolean; onCloseMenu: () => void; onRename: () => void; onMove: () => void; onDownload: () => void; onDelete: () => void; onRestore: () => void; onStar: () => void; folders?: { id: string; name: string }[] };
type MenuProps = Pick<CardProps, "file" | "onMenu" | "menuOpen" | "onCloseMenu" | "onOpen" | "onRename" | "onMove" | "onDownload" | "onDelete" | "onRestore">;
function FileCard({ file, selected, onToggle, onOpen, onMenu, menuOpen, onCloseMenu, onRename, onMove, onDownload, onDelete, onRestore, onStar }: CardProps) { return <article className={selected ? "of-file-card is-selected" : "of-file-card"}><button className="of-select-box" onClick={onToggle} aria-label={`Select ${file.name}`}>{selected && <Check size={13} />}</button><button className="of-file-open" onClick={onOpen}><FileVisual type={file.type} size="xl" /><span><strong>{file.name}</strong><small>{fileTypeLabel[file.type]} · {relativeDate(file.updatedAt)}</small></span></button><div className="of-card-end"><button className={file.starred ? "is-starred" : ""} onClick={onStar} aria-label={file.starred ? "Unstar file" : "Star file"}><Star size={16} fill={file.starred ? "currentColor" : "none"} /></button><FileMenu {...{ file, onMenu, menuOpen, onCloseMenu, onOpen, onRename, onMove, onDownload, onDelete, onRestore }} /></div></article>; }
function FileRow({ file, selected, onToggle, onOpen, onMenu, menuOpen, onCloseMenu, onRename, onMove, onDownload, onDelete, onRestore, onStar, folders = [] }: CardProps) { return <div className={selected ? "of-file-row is-selected" : "of-file-row"}><label><input type="checkbox" checked={selected} onChange={onToggle} aria-label={`Select ${file.name}`} /></label><button className="of-file-row-name" onClick={onOpen}><FileVisual type={file.type} size="sm" /><span><strong>{file.name}</strong><small>{fileTypeLabel[file.type]} · {formatSize(file.size)}</small></span></button><span className="of-owner">{file.shared ? "Shared" : "You"}</span><span>{relativeDate(file.updatedAt)}</span><span>{folders.find(folder => folder.id === file.parentFolderId)?.name || "My files"}</span><div className="of-row-menu"><button className={file.starred ? "is-starred" : ""} onClick={onStar} aria-label={file.starred ? "Unstar file" : "Star file"}><Star size={16} fill={file.starred ? "currentColor" : "none"} /></button><FileMenu {...{ file, onMenu, menuOpen, onCloseMenu, onOpen, onRename, onMove, onDownload, onDelete, onRestore }} /></div></div>; }
function FileMenu({ file, onMenu, menuOpen, onCloseMenu, onOpen, onRename, onMove, onDownload, onDelete, onRestore }: MenuProps) { return <div className="of-row-menu"><button onClick={onMenu} aria-label={`Actions for ${file.name}`}><MoreHorizontal size={18} /></button>{menuOpen && <div className="of-mini-menu"><button onClick={() => { onOpen(); onCloseMenu(); }}>Open</button>{file.trashed ? <button onClick={() => { onRestore(); onCloseMenu(); }}><RotateCcw size={15} /> Restore</button> : <><button onClick={() => { onRename(); onCloseMenu(); }}><Pencil size={15} /> Rename</button><button onClick={() => { onMove(); onCloseMenu(); }}><MoveRight size={15} /> Move</button><button onClick={() => { onDownload(); onCloseMenu(); }}><Download size={15} /> Download</button></>}<button className="is-danger" onClick={() => { onDelete(); onCloseMenu(); }}><Trash2 size={15} /> {file.trashed ? "Delete forever" : "Delete"}</button></div>}</div>; }
